// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl_7PlRCkrCCmPszyPh3cmiTz65uXIfV0',
    appId: '1:991782044935:web:59ae75f890941fcdfa71a2',
    messagingSenderId: '991782044935',
    projectId: 'emanagement-3a7b8',
    authDomain: 'emanagement-3a7b8.firebaseapp.com',
    storageBucket: 'emanagement-3a7b8.firebasestorage.app',
    measurementId: 'G-J430K8MP69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaAvhe5zICZeTiP9PM3UxkJAxTJinInbA',
    appId: '1:991782044935:android:9fd47a45fb6f3077fa71a2',
    messagingSenderId: '991782044935',
    projectId: 'emanagement-3a7b8',
    storageBucket: 'emanagement-3a7b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9bFJI728R2B0xplyzHtk1g8WU0Pxyx8U',
    appId: '1:991782044935:ios:deef3de63a022c2afa71a2',
    messagingSenderId: '991782044935',
    projectId: 'emanagement-3a7b8',
    storageBucket: 'emanagement-3a7b8.firebasestorage.app',
    iosBundleId: 'com.example.eManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9bFJI728R2B0xplyzHtk1g8WU0Pxyx8U',
    appId: '1:991782044935:ios:deef3de63a022c2afa71a2',
    messagingSenderId: '991782044935',
    projectId: 'emanagement-3a7b8',
    storageBucket: 'emanagement-3a7b8.firebasestorage.app',
    iosBundleId: 'com.example.eManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl_7PlRCkrCCmPszyPh3cmiTz65uXIfV0',
    appId: '1:991782044935:web:fb12a8f16342dc89fa71a2',
    messagingSenderId: '991782044935',
    projectId: 'emanagement-3a7b8',
    authDomain: 'emanagement-3a7b8.firebaseapp.com',
    storageBucket: 'emanagement-3a7b8.firebasestorage.app',
    measurementId: 'G-WV2HEZ9DVS',
  );
}
